[package]
name = "rid_ffi"
version = "0.1.0"
authors = ["Thorsten Lorenz <thlorenz@gmx.de>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
rid_common = { path = "../rid-common" }

[[bin]]
name = "main"
path = "./src/main.rs"
